In [3]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

print ('pandas', pd.__version__)
print ('numpy', np.__version__)

pandas 3.0.3
numpy 2.5.1

Seme di riproducibilità

In [4]:
np.random.seed(42)

In [5]:
# Carica il file CSV in un DataFrame
df = pd.read_csv("ADNIMERGE_05Mar2026.csv")

# Visualizza le prime righe del file
print(df.head())

   RID COLPROT ORIGPROT        PTID  SITE VISCODE    EXAMDATE DX_bl   AGE  \
0    2   ADNI1    ADNI1  011_S_0002    11      bl  2005-09-08    CN  74.3
1    3   ADNI1    ADNI1  011_S_0003    11      bl  2005-09-12    AD  81.3
2    3   ADNI1    ADNI1  011_S_0003    11     m06  2006-03-13    AD  81.3
3    3   ADNI1    ADNI1  011_S_0003    11     m12  2006-09-12    AD  81.3
4    3   ADNI1    ADNI1  011_S_0003    11     m24  2007-09-12    AD  81.3

  PTGENDER  ...  PTAU_bl   FDG_bl PIB_bl AV45_bl  FBB_bl  Years_bl  Month_bl  \
0     Male  ...      NaN  1.33615    NaN     NaN     NaN  0.000000   0.00000
1     Male  ...    22.83  1.10860    NaN     NaN     NaN  0.000000   0.00000
2     Male  ...    22.83  1.10860    NaN     NaN     NaN  0.498289   5.96721
3     Male  ...    22.83  1.10860    NaN     NaN     NaN  0.999316  11.96720
4     Male  ...    22.83  1.10860    NaN     NaN     NaN  1.998630  23.93440

   Month   M         update_stamp
0      0   0  2023-07-07 04:59:40
1      0   0  2023-07-07 04:59:40
2      6   6  2023-07-07 04:59:40
3     12  12  2023-07-07 04:59:40
4     24  24  2023-07-07 04:59:40

[5 rows x 116 columns]

C:\Users\ifabb\AppData\Local\Temp\ipykernel_13612\1898293904.py:2: DtypeWarning: Columns (0: ABETA, 1: TAU, 2: PTAU, 3: FLDSTRENG, 4: FSVERSION, 5: ABETA_bl, 6: TAU_bl, 7: PTAU_bl) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("ADNIMERGE_05Mar2026.csv")

Describe() --> Utilizzando il parametro include='all' possiamo generare un riepilogo per tutte le colonne del DataFrame, indipendentemente dal tipo di dati. Questo è utile quando si desidera analizzare contemporaneamente dati numerici e categorici.

In [6]:
print(df.describe(include='all'))

                 RID COLPROT ORIGPROT        PTID          SITE VISCODE  \
count   16421.000000   16421    16421       16421  16421.000000   16421
unique           NaN       4        4        2430           NaN      37
top              NaN   ADNI2    ADNI1  126_S_0605           NaN      bl
freq             NaN    6945     7267          25           NaN    2430
mean     2899.082273     NaN      NaN         NaN     81.733329     NaN
std      2220.442824     NaN      NaN         NaN    132.762777     NaN
min         2.000000     NaN      NaN         NaN      2.000000     NaN
25%       751.000000     NaN      NaN         NaN     22.000000     NaN
50%      2308.000000     NaN      NaN         NaN     41.000000     NaN
75%      4707.000000     NaN      NaN         NaN    123.000000     NaN
max      7125.000000     NaN      NaN         NaN    941.000000     NaN

          EXAMDATE  DX_bl           AGE PTGENDER  ...  PTAU_bl        FDG_bl  \
count        16421  16410  16412.000000    16421  ...    10083  11220.000000
unique        4071      5           NaN        2  ...     1409           NaN
top     2012-02-15   LMCI           NaN     Male  ...    18.85           NaN
freq            19   5275           NaN     8981  ...       34           NaN
mean           NaN    NaN     73.214173      NaN  ...      NaN      1.226786
std            NaN    NaN      7.028099      NaN  ...      NaN      0.153364
min            NaN    NaN     50.400000      NaN  ...      NaN      0.621933
25%            NaN    NaN     68.500000      NaN  ...      NaN      1.134820
50%            NaN    NaN     73.200000      NaN  ...      NaN      1.234580
75%            NaN    NaN     78.100000      NaN  ...      NaN      1.331470
max            NaN    NaN     91.400000      NaN  ...      NaN      1.776170

            PIB_bl      AV45_bl       FBB_bl      Years_bl      Month_bl  \
count   154.000000  7836.000000  1099.000000  16421.000000  16421.000000
unique         NaN          NaN          NaN           NaN           NaN
top            NaN          NaN          NaN           NaN           NaN
freq           NaN          NaN          NaN           NaN           NaN
mean      1.582256     1.186525     1.163109      2.738280     32.792027
std       0.302114     0.220110     0.236850      2.939675     35.203809
min       1.155000     0.810000     0.870200      0.000000      0.000000
25%       1.360000     1.012400     0.995100      0.506502      6.065570
50%       1.490000     1.098400     1.041700      1.960300     23.475400
75%       1.835000     1.346900     1.318600      4.010950     48.032800
max       2.282500     2.010100     1.909000     16.961000    203.115000

               Month             M         update_stamp
count   16421.000000  16421.000000                16421
unique           NaN           NaN                   83
top              NaN           NaN  2023-07-07 04:59:48
freq             NaN           NaN                  914
mean       32.712259     32.580903                  NaN
std        35.193789     35.124178                  NaN
min         0.000000      0.000000                  NaN
25%         6.000000      6.000000                  NaN
50%        24.000000     24.000000                  NaN
75%        48.000000     48.000000                  NaN
max       204.000000    204.000000                  NaN

[11 rows x 116 columns]

Visualizzare il nome delle variabili per colonna

In [7]:
print(df.columns.tolist())

['RID', 'COLPROT', 'ORIGPROT', 'PTID', 'SITE', 'VISCODE', 'EXAMDATE', 'DX_bl', 'AGE', 'PTGENDER', 'PTEDUCAT', 'PTETHCAT', 'PTRACCAT', 'PTMARRY', 'APOE4', 'FDG', 'PIB', 'AV45', 'FBB', 'ABETA', 'TAU', 'PTAU', 'CDRSB', 'ADAS11', 'ADAS13', 'ADASQ4', 'MMSE', 'RAVLT_immediate', 'RAVLT_learning', 'RAVLT_forgetting', 'RAVLT_perc_forgetting', 'LDELTOTAL', 'DIGITSCOR', 'TRABSCOR', 'FAQ', 'MOCA', 'EcogPtMem', 'EcogPtLang', 'EcogPtVisspat', 'EcogPtPlan', 'EcogPtOrgan', 'EcogPtDivatt', 'EcogPtTotal', 'EcogSPMem', 'EcogSPLang', 'EcogSPVisspat', 'EcogSPPlan', 'EcogSPOrgan', 'EcogSPDivatt', 'EcogSPTotal', 'FLDSTRENG', 'FSVERSION', 'IMAGEUID', 'Ventricles', 'Hippocampus', 'WholeBrain', 'Entorhinal', 'Fusiform', 'MidTemp', 'ICV', 'DX', 'mPACCdigit', 'mPACCtrailsB', 'EXAMDATE_bl', 'CDRSB_bl', 'ADAS11_bl', 'ADAS13_bl', 'ADASQ4_bl', 'MMSE_bl', 'RAVLT_immediate_bl', 'RAVLT_learning_bl', 'RAVLT_forgetting_bl', 'RAVLT_perc_forgetting_bl', 'LDELTOTAL_BL', 'DIGITSCOR_bl', 'TRABSCOR_bl', 'FAQ_bl', 'mPACCdigit_bl', 'mPACCtrailsB_bl', 'FLDSTRENG_bl', 'FSVERSION_bl', 'IMAGEUID_bl', 'Ventricles_bl', 'Hippocampus_bl', 'WholeBrain_bl', 'Entorhinal_bl', 'Fusiform_bl', 'MidTemp_bl', 'ICV_bl', 'MOCA_bl', 'EcogPtMem_bl', 'EcogPtLang_bl', 'EcogPtVisspat_bl', 'EcogPtPlan_bl', 'EcogPtOrgan_bl', 'EcogPtDivatt_bl', 'EcogPtTotal_bl', 'EcogSPMem_bl', 'EcogSPLang_bl', 'EcogSPVisspat_bl', 'EcogSPPlan_bl', 'EcogSPOrgan_bl', 'EcogSPDivatt_bl', 'EcogSPTotal_bl', 'ABETA_bl', 'TAU_bl', 'PTAU_bl', 'FDG_bl', 'PIB_bl', 'AV45_bl', 'FBB_bl', 'Years_bl', 'Month_bl', 'Month', 'M', 'update_stamp']

In [8]:
for col in df.columns:
    print(col)

RID
COLPROT
ORIGPROT
PTID
SITE
VISCODE
EXAMDATE
DX_bl
AGE
PTGENDER
PTEDUCAT
PTETHCAT
PTRACCAT
PTMARRY
APOE4
FDG
PIB
AV45
FBB
ABETA
TAU
PTAU
CDRSB
ADAS11
ADAS13
ADASQ4
MMSE
RAVLT_immediate
RAVLT_learning
RAVLT_forgetting
RAVLT_perc_forgetting
LDELTOTAL
DIGITSCOR
TRABSCOR
FAQ
MOCA
EcogPtMem
EcogPtLang
EcogPtVisspat
EcogPtPlan
EcogPtOrgan
EcogPtDivatt
EcogPtTotal
EcogSPMem
EcogSPLang
EcogSPVisspat
EcogSPPlan
EcogSPOrgan
EcogSPDivatt
EcogSPTotal
FLDSTRENG
FSVERSION
IMAGEUID
Ventricles
Hippocampus
WholeBrain
Entorhinal
Fusiform
MidTemp
ICV
DX
mPACCdigit
mPACCtrailsB
EXAMDATE_bl
CDRSB_bl
ADAS11_bl
ADAS13_bl
ADASQ4_bl
MMSE_bl
RAVLT_immediate_bl
RAVLT_learning_bl
RAVLT_forgetting_bl
RAVLT_perc_forgetting_bl
LDELTOTAL_BL
DIGITSCOR_bl
TRABSCOR_bl
FAQ_bl
mPACCdigit_bl
mPACCtrailsB_bl
FLDSTRENG_bl
FSVERSION_bl
IMAGEUID_bl
Ventricles_bl
Hippocampus_bl
WholeBrain_bl
Entorhinal_bl
Fusiform_bl
MidTemp_bl
ICV_bl
MOCA_bl
EcogPtMem_bl
EcogPtLang_bl
EcogPtVisspat_bl
EcogPtPlan_bl
EcogPtOrgan_bl
EcogPtDivatt_bl
EcogPtTotal_bl
EcogSPMem_bl
EcogSPLang_bl
EcogSPVisspat_bl
EcogSPPlan_bl
EcogSPOrgan_bl
EcogSPDivatt_bl
EcogSPTotal_bl
ABETA_bl
TAU_bl
PTAU_bl
FDG_bl
PIB_bl
AV45_bl
FBB_bl
Years_bl
Month_bl
Month
M
update_stamp

In [9]:
print(f"Numero di colonne: {len(df.columns)}")

Numero di colonne: 116

Trovare i valori Nan o nulli per ogni colonna con un ciclo for

In [10]:
for col in df.columns:
    num_null = df[col].isna().sum()
    perc_null = (num_null / len(df)) * 100

    print(f"\nColonna: {col}")
    print(f"Valori nulli: {num_null}")
    print(f"Percentuale nulli: {perc_null:.2f}%")

Colonna: RID
Valori nulli: 0
Percentuale nulli: 0.00%

Colonna: COLPROT
Valori nulli: 0
Percentuale nulli: 0.00%

Colonna: ORIGPROT
Valori nulli: 0
Percentuale nulli: 0.00%

Colonna: PTID
Valori nulli: 0
Percentuale nulli: 0.00%

Colonna: SITE
Valori nulli: 0
Percentuale nulli: 0.00%

Colonna: VISCODE
Valori nulli: 0
Percentuale nulli: 0.00%

Colonna: EXAMDATE
Valori nulli: 0
Percentuale nulli: 0.00%

Colonna: DX_bl
Valori nulli: 11
Percentuale nulli: 0.07%

Colonna: AGE
Valori nulli: 9
Percentuale nulli: 0.05%

Colonna: PTGENDER
Valori nulli: 0
Percentuale nulli: 0.00%

Colonna: PTEDUCAT
Valori nulli: 0
Percentuale nulli: 0.00%

Colonna: PTETHCAT
Valori nulli: 0
Percentuale nulli: 0.00%

Colonna: PTRACCAT
Valori nulli: 0
Percentuale nulli: 0.00%

Colonna: PTMARRY
Valori nulli: 1
Percentuale nulli: 0.01%

Colonna: APOE4
Valori nulli: 365
Percentuale nulli: 2.22%

Colonna: FDG
Valori nulli: 12728
Percentuale nulli: 77.51%

Colonna: PIB
Valori nulli: 16198
Percentuale nulli: 98.64%

Colonna: AV45
Valori nulli: 13341
Percentuale nulli: 81.24%

Colonna: FBB
Valori nulli: 15908
Percentuale nulli: 96.88%

Colonna: ABETA
Valori nulli: 14051
Percentuale nulli: 85.57%

Colonna: TAU
Valori nulli: 14051
Percentuale nulli: 85.57%

Colonna: PTAU
Valori nulli: 14052
Percentuale nulli: 85.57%

Colonna: CDRSB
Valori nulli: 4674
Percentuale nulli: 28.46%

Colonna: ADAS11
Valori nulli: 4990
Percentuale nulli: 30.39%

Colonna: ADAS13
Valori nulli: 5091
Percentuale nulli: 31.00%

Colonna: ADASQ4
Valori nulli: 4954
Percentuale nulli: 30.17%

Colonna: MMSE
Valori nulli: 4952
Percentuale nulli: 30.16%

Colonna: RAVLT_immediate
Valori nulli: 5075
Percentuale nulli: 30.91%

Colonna: RAVLT_learning
Valori nulli: 5074
Percentuale nulli: 30.90%

Colonna: RAVLT_forgetting
Valori nulli: 5106
Percentuale nulli: 31.09%

Colonna: RAVLT_perc_forgetting
Valori nulli: 5179
Percentuale nulli: 31.54%

Colonna: LDELTOTAL
Valori nulli: 6979
Percentuale nulli: 42.50%

Colonna: DIGITSCOR
Valori nulli: 12621
Percentuale nulli: 76.86%

Colonna: TRABSCOR
Valori nulli: 5412
Percentuale nulli: 32.96%

Colonna: FAQ
Valori nulli: 4678
Percentuale nulli: 28.49%

Colonna: MOCA
Valori nulli: 8995
Percentuale nulli: 54.78%

Colonna: EcogPtMem
Valori nulli: 8645
Percentuale nulli: 52.65%

Colonna: EcogPtLang
Valori nulli: 8662
Percentuale nulli: 52.75%

Colonna: EcogPtVisspat
Valori nulli: 8745
Percentuale nulli: 53.25%

Colonna: EcogPtPlan
Valori nulli: 8681
Percentuale nulli: 52.87%

Colonna: EcogPtOrgan
Valori nulli: 8823
Percentuale nulli: 53.73%

Colonna: EcogPtDivatt
Valori nulli: 8721
Percentuale nulli: 53.11%

Colonna: EcogPtTotal
Valori nulli: 8655
Percentuale nulli: 52.71%

Colonna: EcogSPMem
Valori nulli: 8602
Percentuale nulli: 52.38%

Colonna: EcogSPLang
Valori nulli: 8596
Percentuale nulli: 52.35%

Colonna: EcogSPVisspat
Valori nulli: 8782
Percentuale nulli: 53.48%

Colonna: EcogSPPlan
Valori nulli: 8686
Percentuale nulli: 52.90%

Colonna: EcogSPOrgan
Valori nulli: 8933
Percentuale nulli: 54.40%

Colonna: EcogSPDivatt
Valori nulli: 8804
Percentuale nulli: 53.61%

Colonna: EcogSPTotal
Valori nulli: 8604
Percentuale nulli: 52.40%

Colonna: FLDSTRENG
Valori nulli: 8762
Percentuale nulli: 53.36%

Colonna: FSVERSION
Valori nulli: 6289
Percentuale nulli: 38.30%

Colonna: IMAGEUID
Valori nulli: 6289
Percentuale nulli: 38.30%

Colonna: Ventricles
Valori nulli: 6953
Percentuale nulli: 42.34%

Colonna: Hippocampus
Valori nulli: 7568
Percentuale nulli: 46.09%

Colonna: WholeBrain
Valori nulli: 6679
Percentuale nulli: 40.67%

Colonna: Entorhinal
Valori nulli: 7981
Percentuale nulli: 48.60%

Colonna: Fusiform
Valori nulli: 7981
Percentuale nulli: 48.60%

Colonna: MidTemp
Valori nulli: 7981
Percentuale nulli: 48.60%

Colonna: ICV
Valori nulli: 6306
Percentuale nulli: 38.40%

Colonna: DX
Valori nulli: 4963
Percentuale nulli: 30.22%

Colonna: mPACCdigit
Valori nulli: 4949
Percentuale nulli: 30.14%

Colonna: mPACCtrailsB
Valori nulli: 4943
Percentuale nulli: 30.10%

Colonna: EXAMDATE_bl
Valori nulli: 0
Percentuale nulli: 0.00%

Colonna: CDRSB_bl
Valori nulli: 0
Percentuale nulli: 0.00%

Colonna: ADAS11_bl
Valori nulli: 40
Percentuale nulli: 0.24%

Colonna: ADAS13_bl
Valori nulli: 112
Percentuale nulli: 0.68%

Colonna: ADASQ4_bl
Valori nulli: 7
Percentuale nulli: 0.04%

Colonna: MMSE_bl
Valori nulli: 2
Percentuale nulli: 0.01%

Colonna: RAVLT_immediate_bl
Valori nulli: 41
Percentuale nulli: 0.25%

Colonna: RAVLT_learning_bl
Valori nulli: 41
Percentuale nulli: 0.25%

Colonna: RAVLT_forgetting_bl
Valori nulli: 44
Percentuale nulli: 0.27%

Colonna: RAVLT_perc_forgetting_bl
Valori nulli: 65
Percentuale nulli: 0.40%

Colonna: LDELTOTAL_BL
Valori nulli: 5
Percentuale nulli: 0.03%

Colonna: DIGITSCOR_bl
Valori nulli: 9171
Percentuale nulli: 55.85%

Colonna: TRABSCOR_bl
Valori nulli: 267
Percentuale nulli: 1.63%

Colonna: FAQ_bl
Valori nulli: 86
Percentuale nulli: 0.52%

Colonna: mPACCdigit_bl
Valori nulli: 3
Percentuale nulli: 0.02%

Colonna: mPACCtrailsB_bl
Valori nulli: 3
Percentuale nulli: 0.02%

Colonna: FLDSTRENG_bl
Valori nulli: 3425
Percentuale nulli: 20.86%

Colonna: FSVERSION_bl
Valori nulli: 261
Percentuale nulli: 1.59%

Colonna: IMAGEUID_bl
Valori nulli: 261
Percentuale nulli: 1.59%

Colonna: Ventricles_bl
Valori nulli: 778
Percentuale nulli: 4.74%

Colonna: Hippocampus_bl
Valori nulli: 2149
Percentuale nulli: 13.09%

Colonna: WholeBrain_bl
Valori nulli: 476
Percentuale nulli: 2.90%

Colonna: Entorhinal_bl
Valori nulli: 2310
Percentuale nulli: 14.07%

Colonna: Fusiform_bl
Valori nulli: 2310
Percentuale nulli: 14.07%

Colonna: MidTemp_bl
Valori nulli: 2310
Percentuale nulli: 14.07%

Colonna: ICV_bl
Valori nulli: 263
Percentuale nulli: 1.60%

Colonna: MOCA_bl
Valori nulli: 7423
Percentuale nulli: 45.20%

Colonna: EcogPtMem_bl
Valori nulli: 7306
Percentuale nulli: 44.49%

Colonna: EcogPtLang_bl
Valori nulli: 7315
Percentuale nulli: 44.55%

Colonna: EcogPtVisspat_bl
Valori nulli: 7349
Percentuale nulli: 44.75%

Colonna: EcogPtPlan_bl
Valori nulli: 7305
Percentuale nulli: 44.49%

Colonna: EcogPtOrgan_bl
Valori nulli: 7489
Percentuale nulli: 45.61%

Colonna: EcogPtDivatt_bl
Valori nulli: 7361
Percentuale nulli: 44.83%

Colonna: EcogPtTotal_bl
Valori nulli: 7304
Percentuale nulli: 44.48%

Colonna: EcogSPMem_bl
Valori nulli: 7338
Percentuale nulli: 44.69%

Colonna: EcogSPLang_bl
Valori nulli: 7327
Percentuale nulli: 44.62%

Colonna: EcogSPVisspat_bl
Valori nulli: 7460
Percentuale nulli: 45.43%

Colonna: EcogSPPlan_bl
Valori nulli: 7389
Percentuale nulli: 45.00%

Colonna: EcogSPOrgan_bl
Valori nulli: 7742
Percentuale nulli: 47.15%

Colonna: EcogSPDivatt_bl
Valori nulli: 7506
Percentuale nulli: 45.71%

Colonna: EcogSPTotal_bl
Valori nulli: 7336
Percentuale nulli: 44.67%

Colonna: ABETA_bl
Valori nulli: 6338
Percentuale nulli: 38.60%

Colonna: TAU_bl
Valori nulli: 6338
Percentuale nulli: 38.60%

Colonna: PTAU_bl
Valori nulli: 6338
Percentuale nulli: 38.60%

Colonna: FDG_bl
Valori nulli: 5201
Percentuale nulli: 31.67%

Colonna: PIB_bl
Valori nulli: 16267
Percentuale nulli: 99.06%

Colonna: AV45_bl
Valori nulli: 8585
Percentuale nulli: 52.28%

Colonna: FBB_bl
Valori nulli: 15322
Percentuale nulli: 93.31%

Colonna: Years_bl
Valori nulli: 0
Percentuale nulli: 0.00%

Colonna: Month_bl
Valori nulli: 0
Percentuale nulli: 0.00%

Colonna: Month
Valori nulli: 0
Percentuale nulli: 0.00%

Colonna: M
Valori nulli: 0
Percentuale nulli: 0.00%

Colonna: update_stamp
Valori nulli: 0
Percentuale nulli: 0.00%

In ordine dal più sporco al più pulito

In [11]:
null_summary = pd.DataFrame({
    'colonna': df.columns,
    'null_count': [df[col].isna().sum() for col in df.columns],
    'null_percent': [(df[col].isna().sum() / len(df)) * 100 for col in df.columns]
})

print(null_summary.sort_values('null_count', ascending=False))

          colonna  null_count  null_percent
108        PIB_bl       16267     99.062176
16            PIB       16198     98.641983
18            FBB       15908     96.875952
110        FBB_bl       15322     93.307350
21           PTAU       14052     85.573351
..            ...         ...           ...
111      Years_bl           0      0.000000
112      Month_bl           0      0.000000
113         Month           0      0.000000
114             M           0      0.000000
115  update_stamp           0      0.000000

[116 rows x 3 columns]

Solo le colonne che superano il 40% di valori nulli

In [12]:
count = 0

for col in df.columns:
    percentuale = df[col].isna().mean() * 100

    if percentuale > 40:
        print(f"{col}: {percentuale:.2f}% nulli")
        count += 1

print(f"\nNumero di colonne con più del 40% di valori nulli: {count}")

FDG: 77.51% nulli
PIB: 98.64% nulli
AV45: 81.24% nulli
FBB: 96.88% nulli
ABETA: 85.57% nulli
TAU: 85.57% nulli
PTAU: 85.57% nulli
LDELTOTAL: 42.50% nulli
DIGITSCOR: 76.86% nulli
MOCA: 54.78% nulli
EcogPtMem: 52.65% nulli
EcogPtLang: 52.75% nulli
EcogPtVisspat: 53.25% nulli
EcogPtPlan: 52.87% nulli
EcogPtOrgan: 53.73% nulli
EcogPtDivatt: 53.11% nulli
EcogPtTotal: 52.71% nulli
EcogSPMem: 52.38% nulli
EcogSPLang: 52.35% nulli
EcogSPVisspat: 53.48% nulli
EcogSPPlan: 52.90% nulli
EcogSPOrgan: 54.40% nulli
EcogSPDivatt: 53.61% nulli
EcogSPTotal: 52.40% nulli
FLDSTRENG: 53.36% nulli
Ventricles: 42.34% nulli
Hippocampus: 46.09% nulli
WholeBrain: 40.67% nulli
Entorhinal: 48.60% nulli
Fusiform: 48.60% nulli
MidTemp: 48.60% nulli
DIGITSCOR_bl: 55.85% nulli
MOCA_bl: 45.20% nulli
EcogPtMem_bl: 44.49% nulli
EcogPtLang_bl: 44.55% nulli
EcogPtVisspat_bl: 44.75% nulli
EcogPtPlan_bl: 44.49% nulli
EcogPtOrgan_bl: 45.61% nulli
EcogPtDivatt_bl: 44.83% nulli
EcogPtTotal_bl: 44.48% nulli
EcogSPMem_bl: 44.69% nulli
EcogSPLang_bl: 44.62% nulli
EcogSPVisspat_bl: 45.43% nulli
EcogSPPlan_bl: 45.00% nulli
EcogSPOrgan_bl: 47.15% nulli
EcogSPDivatt_bl: 45.71% nulli
EcogSPTotal_bl: 44.67% nulli
PIB_bl: 99.06% nulli
AV45_bl: 52.28% nulli
FBB_bl: 93.31% nulli

Numero di colonne con più del 40% di valori nulli: 50

df[col].shape restituisce sempre una tupla del tipo (numero_righe,), perché una singola colonna (Serie pandas) è monodimensionale — quindi il numero sarà uguale per tutte le colonne (pari al numero totale di righe del dataset). Se invece ti interessa lo shape dell'intero DataFrame (righe, colonne), basta:

In [13]:
print(f"Shape del dataset: {df.shape}")

Shape del dataset: (16421, 116)

sommario colonne

In [14]:
for col in df.columns:
    print(f"\n=== {col} ===")
    print(f"Shape: {df[col].shape}")
    print(f"Tipo di dato: {df[col].dtype}")
    print(f"Valori non nulli: {df[col].notna().sum()}")
    print(f"Valori nulli: {df[col].isna().sum()}")

=== RID ===
Shape: (16421,)
Tipo di dato: int64
Valori non nulli: 16421
Valori nulli: 0

=== COLPROT ===
Shape: (16421,)
Tipo di dato: str
Valori non nulli: 16421
Valori nulli: 0

=== ORIGPROT ===
Shape: (16421,)
Tipo di dato: str
Valori non nulli: 16421
Valori nulli: 0

=== PTID ===
Shape: (16421,)
Tipo di dato: str
Valori non nulli: 16421
Valori nulli: 0

=== SITE ===
Shape: (16421,)
Tipo di dato: int64
Valori non nulli: 16421
Valori nulli: 0

=== VISCODE ===
Shape: (16421,)
Tipo di dato: str
Valori non nulli: 16421
Valori nulli: 0

=== EXAMDATE ===
Shape: (16421,)
Tipo di dato: str
Valori non nulli: 16421
Valori nulli: 0

=== DX_bl ===
Shape: (16421,)
Tipo di dato: str
Valori non nulli: 16410
Valori nulli: 11

=== AGE ===
Shape: (16421,)
Tipo di dato: float64
Valori non nulli: 16412
Valori nulli: 9

=== PTGENDER ===
Shape: (16421,)
Tipo di dato: str
Valori non nulli: 16421
Valori nulli: 0

=== PTEDUCAT ===
Shape: (16421,)
Tipo di dato: int64
Valori non nulli: 16421
Valori nulli: 0

=== PTETHCAT ===
Shape: (16421,)
Tipo di dato: str
Valori non nulli: 16421
Valori nulli: 0

=== PTRACCAT ===
Shape: (16421,)
Tipo di dato: str
Valori non nulli: 16421
Valori nulli: 0

=== PTMARRY ===
Shape: (16421,)
Tipo di dato: str
Valori non nulli: 16420
Valori nulli: 1

=== APOE4 ===
Shape: (16421,)
Tipo di dato: float64
Valori non nulli: 16056
Valori nulli: 365

=== FDG ===
Shape: (16421,)
Tipo di dato: float64
Valori non nulli: 3693
Valori nulli: 12728

=== PIB ===
Shape: (16421,)
Tipo di dato: float64
Valori non nulli: 223
Valori nulli: 16198

=== AV45 ===
Shape: (16421,)
Tipo di dato: float64
Valori non nulli: 3080
Valori nulli: 13341

=== FBB ===
Shape: (16421,)
Tipo di dato: float64
Valori non nulli: 513
Valori nulli: 15908

=== ABETA ===
Shape: (16421,)
Tipo di dato: object
Valori non nulli: 2370
Valori nulli: 14051

=== TAU ===
Shape: (16421,)
Tipo di dato: object
Valori non nulli: 2370
Valori nulli: 14051

=== PTAU ===
Shape: (16421,)
Tipo di dato: object
Valori non nulli: 2369
Valori nulli: 14052

=== CDRSB ===
Shape: (16421,)
Tipo di dato: float64
Valori non nulli: 11747
Valori nulli: 4674

=== ADAS11 ===
Shape: (16421,)
Tipo di dato: float64
Valori non nulli: 11431
Valori nulli: 4990

=== ADAS13 ===
Shape: (16421,)
Tipo di dato: float64
Valori non nulli: 11330
Valori nulli: 5091

=== ADASQ4 ===
Shape: (16421,)
Tipo di dato: float64
Valori non nulli: 11467
Valori nulli: 4954

=== MMSE ===
Shape: (16421,)
Tipo di dato: float64
Valori non nulli: 11469
Valori nulli: 4952

=== RAVLT_immediate ===
Shape: (16421,)
Tipo di dato: float64
Valori non nulli: 11346
Valori nulli: 5075

=== RAVLT_learning ===
Shape: (16421,)
Tipo di dato: float64
Valori non nulli: 11347
Valori nulli: 5074

=== RAVLT_forgetting ===
Shape: (16421,)
Tipo di dato: float64
Valori non nulli: 11315
Valori nulli: 5106

=== RAVLT_perc_forgetting ===
Shape: (16421,)
Tipo di dato: float64
Valori non nulli: 11242
Valori nulli: 5179

=== LDELTOTAL ===
Shape: (16421,)
Tipo di dato: float64
Valori non nulli: 9442
Valori nulli: 6979

=== DIGITSCOR ===
Shape: (16421,)
Tipo di dato: float64
Valori non nulli: 3800
Valori nulli: 12621

=== TRABSCOR ===
Shape: (16421,)
Tipo di dato: float64
Valori non nulli: 11009
Valori nulli: 5412

=== FAQ ===
Shape: (16421,)
Tipo di dato: float64
Valori non nulli: 11743
Valori nulli: 4678

=== MOCA ===
Shape: (16421,)
Tipo di dato: float64
Valori non nulli: 7426
Valori nulli: 8995

=== EcogPtMem ===
Shape: (16421,)
Tipo di dato: float64
Valori non nulli: 7776
Valori nulli: 8645

=== EcogPtLang ===
Shape: (16421,)
Tipo di dato: float64
Valori non nulli: 7759
Valori nulli: 8662

=== EcogPtVisspat ===
Shape: (16421,)
Tipo di dato: float64
Valori non nulli: 7676
Valori nulli: 8745

=== EcogPtPlan ===
Shape: (16421,)
Tipo di dato: float64
Valori non nulli: 7740
Valori nulli: 8681

=== EcogPtOrgan ===
Shape: (16421,)
Tipo di dato: float64
Valori non nulli: 7598
Valori nulli: 8823

=== EcogPtDivatt ===
Shape: (16421,)
Tipo di dato: float64
Valori non nulli: 7700
Valori nulli: 8721

=== EcogPtTotal ===
Shape: (16421,)
Tipo di dato: float64
Valori non nulli: 7766
Valori nulli: 8655

=== EcogSPMem ===
Shape: (16421,)
Tipo di dato: float64
Valori non nulli: 7819
Valori nulli: 8602

=== EcogSPLang ===
Shape: (16421,)
Tipo di dato: float64
Valori non nulli: 7825
Valori nulli: 8596

=== EcogSPVisspat ===
Shape: (16421,)
Tipo di dato: float64
Valori non nulli: 7639
Valori nulli: 8782

=== EcogSPPlan ===
Shape: (16421,)
Tipo di dato: float64
Valori non nulli: 7735
Valori nulli: 8686

=== EcogSPOrgan ===
Shape: (16421,)
Tipo di dato: float64
Valori non nulli: 7488
Valori nulli: 8933

=== EcogSPDivatt ===
Shape: (16421,)
Tipo di dato: float64
Valori non nulli: 7617
Valori nulli: 8804

=== EcogSPTotal ===
Shape: (16421,)
Tipo di dato: float64
Valori non nulli: 7817
Valori nulli: 8604

=== FLDSTRENG ===
Shape: (16421,)
Tipo di dato: str
Valori non nulli: 7659
Valori nulli: 8762

=== FSVERSION ===
Shape: (16421,)
Tipo di dato: str
Valori non nulli: 10132
Valori nulli: 6289

=== IMAGEUID ===
Shape: (16421,)
Tipo di dato: float64
Valori non nulli: 10132
Valori nulli: 6289

=== Ventricles ===
Shape: (16421,)
Tipo di dato: float64
Valori non nulli: 9468
Valori nulli: 6953

=== Hippocampus ===
Shape: (16421,)
Tipo di dato: float64
Valori non nulli: 8853
Valori nulli: 7568

=== WholeBrain ===
Shape: (16421,)
Tipo di dato: float64
Valori non nulli: 9742
Valori nulli: 6679

=== Entorhinal ===
Shape: (16421,)
Tipo di dato: float64
Valori non nulli: 8440
Valori nulli: 7981

=== Fusiform ===
Shape: (16421,)
Tipo di dato: float64
Valori non nulli: 8440
Valori nulli: 7981

=== MidTemp ===
Shape: (16421,)
Tipo di dato: float64
Valori non nulli: 8440
Valori nulli: 7981

=== ICV ===
Shape: (16421,)
Tipo di dato: float64
Valori non nulli: 10115
Valori nulli: 6306

=== DX ===
Shape: (16421,)
Tipo di dato: str
Valori non nulli: 11458
Valori nulli: 4963

=== mPACCdigit ===
Shape: (16421,)
Tipo di dato: float64
Valori non nulli: 11472
Valori nulli: 4949

=== mPACCtrailsB ===
Shape: (16421,)
Tipo di dato: float64
Valori non nulli: 11478
Valori nulli: 4943

=== EXAMDATE_bl ===
Shape: (16421,)
Tipo di dato: str
Valori non nulli: 16421
Valori nulli: 0

=== CDRSB_bl ===
Shape: (16421,)
Tipo di dato: float64
Valori non nulli: 16421
Valori nulli: 0

=== ADAS11_bl ===
Shape: (16421,)
Tipo di dato: float64
Valori non nulli: 16381
Valori nulli: 40

=== ADAS13_bl ===
Shape: (16421,)
Tipo di dato: float64
Valori non nulli: 16309
Valori nulli: 112

=== ADASQ4_bl ===
Shape: (16421,)
Tipo di dato: float64
Valori non nulli: 16414
Valori nulli: 7

=== MMSE_bl ===
Shape: (16421,)
Tipo di dato: float64
Valori non nulli: 16419
Valori nulli: 2

=== RAVLT_immediate_bl ===
Shape: (16421,)
Tipo di dato: float64
Valori non nulli: 16380
Valori nulli: 41

=== RAVLT_learning_bl ===
Shape: (16421,)
Tipo di dato: float64
Valori non nulli: 16380
Valori nulli: 41

=== RAVLT_forgetting_bl ===
Shape: (16421,)
Tipo di dato: float64
Valori non nulli: 16377
Valori nulli: 44

=== RAVLT_perc_forgetting_bl ===
Shape: (16421,)
Tipo di dato: float64
Valori non nulli: 16356
Valori nulli: 65

=== LDELTOTAL_BL ===
Shape: (16421,)
Tipo di dato: float64
Valori non nulli: 16416
Valori nulli: 5

=== DIGITSCOR_bl ===
Shape: (16421,)
Tipo di dato: float64
Valori non nulli: 7250
Valori nulli: 9171

=== TRABSCOR_bl ===
Shape: (16421,)
Tipo di dato: float64
Valori non nulli: 16154
Valori nulli: 267

=== FAQ_bl ===
Shape: (16421,)
Tipo di dato: float64
Valori non nulli: 16335
Valori nulli: 86

=== mPACCdigit_bl ===
Shape: (16421,)
Tipo di dato: float64
Valori non nulli: 16418
Valori nulli: 3

=== mPACCtrailsB_bl ===
Shape: (16421,)
Tipo di dato: float64
Valori non nulli: 16418
Valori nulli: 3

=== FLDSTRENG_bl ===
Shape: (16421,)
Tipo di dato: str
Valori non nulli: 12996
Valori nulli: 3425

=== FSVERSION_bl ===
Shape: (16421,)
Tipo di dato: str
Valori non nulli: 16160
Valori nulli: 261

=== IMAGEUID_bl ===
Shape: (16421,)
Tipo di dato: float64
Valori non nulli: 16160
Valori nulli: 261

=== Ventricles_bl ===
Shape: (16421,)
Tipo di dato: float64
Valori non nulli: 15643
Valori nulli: 778

=== Hippocampus_bl ===
Shape: (16421,)
Tipo di dato: float64
Valori non nulli: 14272
Valori nulli: 2149

=== WholeBrain_bl ===
Shape: (16421,)
Tipo di dato: float64
Valori non nulli: 15945
Valori nulli: 476

=== Entorhinal_bl ===
Shape: (16421,)
Tipo di dato: float64
Valori non nulli: 14111
Valori nulli: 2310

=== Fusiform_bl ===
Shape: (16421,)
Tipo di dato: float64
Valori non nulli: 14111
Valori nulli: 2310

=== MidTemp_bl ===
Shape: (16421,)
Tipo di dato: float64
Valori non nulli: 14111
Valori nulli: 2310

=== ICV_bl ===
Shape: (16421,)
Tipo di dato: float64
Valori non nulli: 16158
Valori nulli: 263

=== MOCA_bl ===
Shape: (16421,)
Tipo di dato: float64
Valori non nulli: 8998
Valori nulli: 7423

=== EcogPtMem_bl ===
Shape: (16421,)
Tipo di dato: float64
Valori non nulli: 9115
Valori nulli: 7306

=== EcogPtLang_bl ===
Shape: (16421,)
Tipo di dato: float64
Valori non nulli: 9106
Valori nulli: 7315

=== EcogPtVisspat_bl ===
Shape: (16421,)
Tipo di dato: float64
Valori non nulli: 9072
Valori nulli: 7349

=== EcogPtPlan_bl ===
Shape: (16421,)
Tipo di dato: float64
Valori non nulli: 9116
Valori nulli: 7305

=== EcogPtOrgan_bl ===
Shape: (16421,)
Tipo di dato: float64
Valori non nulli: 8932
Valori nulli: 7489

=== EcogPtDivatt_bl ===
Shape: (16421,)
Tipo di dato: float64
Valori non nulli: 9060
Valori nulli: 7361

=== EcogPtTotal_bl ===
Shape: (16421,)
Tipo di dato: float64
Valori non nulli: 9117
Valori nulli: 7304

=== EcogSPMem_bl ===
Shape: (16421,)
Tipo di dato: float64
Valori non nulli: 9083
Valori nulli: 7338

=== EcogSPLang_bl ===
Shape: (16421,)
Tipo di dato: float64
Valori non nulli: 9094
Valori nulli: 7327

=== EcogSPVisspat_bl ===
Shape: (16421,)
Tipo di dato: float64
Valori non nulli: 8961
Valori nulli: 7460

=== EcogSPPlan_bl ===
Shape: (16421,)
Tipo di dato: float64
Valori non nulli: 9032
Valori nulli: 7389

=== EcogSPOrgan_bl ===
Shape: (16421,)
Tipo di dato: float64
Valori non nulli: 8679
Valori nulli: 7742

=== EcogSPDivatt_bl ===
Shape: (16421,)
Tipo di dato: float64
Valori non nulli: 8915
Valori nulli: 7506

=== EcogSPTotal_bl ===
Shape: (16421,)
Tipo di dato: float64
Valori non nulli: 9085
Valori nulli: 7336

=== ABETA_bl ===
Shape: (16421,)
Tipo di dato: object
Valori non nulli: 10083
Valori nulli: 6338

=== TAU_bl ===
Shape: (16421,)
Tipo di dato: object
Valori non nulli: 10083
Valori nulli: 6338

=== PTAU_bl ===
Shape: (16421,)
Tipo di dato: object
Valori non nulli: 10083
Valori nulli: 6338

=== FDG_bl ===
Shape: (16421,)
Tipo di dato: float64
Valori non nulli: 11220
Valori nulli: 5201

=== PIB_bl ===
Shape: (16421,)
Tipo di dato: float64
Valori non nulli: 154
Valori nulli: 16267

=== AV45_bl ===
Shape: (16421,)
Tipo di dato: float64
Valori non nulli: 7836
Valori nulli: 8585

=== FBB_bl ===
Shape: (16421,)
Tipo di dato: float64
Valori non nulli: 1099
Valori nulli: 15322

=== Years_bl ===
Shape: (16421,)
Tipo di dato: float64
Valori non nulli: 16421
Valori nulli: 0

=== Month_bl ===
Shape: (16421,)
Tipo di dato: float64
Valori non nulli: 16421
Valori nulli: 0

=== Month ===
Shape: (16421,)
Tipo di dato: int64
Valori non nulli: 16421
Valori nulli: 0

=== M ===
Shape: (16421,)
Tipo di dato: int64
Valori non nulli: 16421
Valori nulli: 0

=== update_stamp ===
Shape: (16421,)
Tipo di dato: str
Valori non nulli: 16421
Valori nulli: 0

Verifico se le date sono tutte valide, se sono scritte con un formato diverso o se sono mancanti oppure Nan

In [16]:
# 2. Estrai solo il "formato" di ogni data, ignorando i valori specifici
#    Esempio: "2023-05-14" -> "dddd-dd-dd"
#             "14/05/2023" -> "dd/dd/dddd"

import re
import pandas as pd

col_data = "EXAMDATE"  # sostituisci con il nome esatto della colonna date nel tuo dataset

def estrai_formato(valore):
    if pd.isna(valore):
        return "NaN"
    valore = str(valore)
    return re.sub(r'\d', 'd', valore)

formati = df[col_data].apply(estrai_formato)

print("\nFormati distinti trovati nella colonna:")
print(formati.value_counts())

Formati distinti trovati nella colonna:
EXAMDATE
dddd-dd-dd    16421
Name: count, dtype: int64

In [ ]:
# 3. Prova a convertire in formato datetime e individua i valori problematici
date_convertite = pd.to_datetime(df[col_data], errors='coerce')

# Righe che NON sono state convertite correttamente (ma non erano già NaN in origine)
problemi = df[df[col_data].notna() & date_convertite.isna()]

print(f"\nNumero di valori data non convertibili: {len(problemi)}")
print(problemi[[col_data]])

Numero di valori data non convertibili: 0
Empty DataFrame
Columns: [EXAMDATE]
Index: []

Valori mancanti colonna "EXAMDATE"

In [19]:
# Numero e percentuale di valori mancanti nella colonna date
nulli = df[col_data].isna().sum()
totali = len(df)
percentuale = (nulli / totali) * 100

print(f"Valori mancanti in '{col_data}': {nulli}/{totali} ({percentuale:.2f}%)")

Valori mancanti in 'EXAMDATE': 0/16421 (0.00%)

Controllare la validità della collona AGE

In [21]:
col_age = "AGE"

# 1. Valori mancanti
nulli = df[col_age].isna().sum()
totali = len(df)
percentuale = (nulli / totali) * 100
print(f"Valori mancanti in '{col_age}': {nulli}/{totali} ({percentuale:.2f}%)")

# 2. Statistiche descrittive di base (min, max, media, mediana, ecc.)
print(f"\nStatistiche descrittive di '{col_age}':")
print(df[col_age].describe())

# 3. Tipo di dato (deve essere numerico)
print(f"\nTipo di dato: {df[col_age].dtype}")

# 4. Controllo range plausibile (in ADNI i partecipanti sono adulti, tipicamente 55-95 anni)
eta_min_plausibile = 18   # nessun paziente dovrebbe avere meno di 18 anni
eta_max_plausibile = 110  # nessun paziente dovrebbe avere più di 110 anni

fuori_range = df[(df[col_age] < eta_min_plausibile) | (df[col_age] > eta_max_plausibile)]
print(f"\nRighe con età fuori range plausibile ({eta_min_plausibile}-{eta_max_plausibile}): {len(fuori_range)}")
print(fuori_range[[col_age]])

# 5. Valori negativi o pari a zero (chiaramente errati)
invalidi = df[df[col_age] <= 0]
print(f"\nValori di età <= 0: {len(invalidi)}")
print(invalidi[[col_age]])

# 6. Valori non numerici mascherati da stringhe (es. spazi vuoti, "NA" scritto come testo)
non_numerici = df[pd.to_numeric(df[col_age], errors='coerce').isna() & df[col_age].notna()]
print(f"\nValori non numerici in '{col_age}': {len(non_numerici)}")
print(non_numerici[[col_age]])

Valori mancanti in 'AGE': 9/16421 (0.05%)

Statistiche descrittive di 'AGE':
count    16412.000000
mean        73.214173
std          7.028099
min         50.400000
25%         68.500000
50%         73.200000
75%         78.100000
max         91.400000
Name: AGE, dtype: float64

Tipo di dato: float64

Righe con età fuori range plausibile (18-110): 0
Empty DataFrame
Columns: [AGE]
Index: []

Valori di età <= 0: 0
Empty DataFrame
Columns: [AGE]
Index: []

Valori non numerici in 'AGE': 0
Empty DataFrame
Columns: [AGE]
Index: []

Valori mancanti

In [22]:
righe_age_mancante = df[df["AGE"].isna()]
print(f"Numero di righe con AGE mancante: {len(righe_age_mancante)}")
righe_age_mancante

Numero di righe con AGE mancante: 9

,RID,COLPROT,ORIGPROT,PTID,SITE,VISCODE,EXAMDATE,DX_bl,AGE,PTGENDER,...,PTAU_bl,FDG_bl,PIB_bl,AV45_bl,FBB_bl,Years_bl,Month_bl,Month,M,update_stamp
13181,6861,ADNI3,ADNI3,053_S_6861,53,bl,2020-03-10,EMCI,NaN,Male,...,NaN,NaN,NaN,NaN,NaN,0.00000,0.0000,0,0,2023-07-07 05:00:05
13290,6861,ADNI3,ADNI3,053_S_6861,53,m12,2021-05-27,EMCI,NaN,Male,...,NaN,NaN,NaN,NaN,NaN,1.21287,14.5246,12,12,2023-07-07 05:00:05
15212,6505,ADNI3,ADNI3,029_S_6505,29,bl,2018-09-14,CN,NaN,Female,...,NaN,1.31579,NaN,NaN,1.3252,0.00000,0.0000,0,0,2023-07-07 05:00:04
15349,6598,ADNI3,ADNI3,053_S_6598,53,bl,2018-10-22,LMCI,NaN,Male,...,NaN,1.38965,NaN,1.4515,NaN,0.00000,0.0000,0,0,2023-07-07 05:00:04
15350,6598,ADNI3,ADNI3,053_S_6598,53,m12,2019-10-29,LMCI,NaN,Male,...,NaN,1.38965,NaN,1.4515,NaN,1.01848,12.1967,12,12,2023-07-07 05:00:04
15351,6598,ADNI3,ADNI3,053_S_6598,53,m30,2021-05-03,LMCI,NaN,Male,...,NaN,1.38965,NaN,1.4515,NaN,2.52977,30.2951,30,30,2023-07-07 05:00:04
15551,6832,ADNI3,ADNI3,052_S_6832,52,bl,2020-01-09,LMCI,NaN,Male,...,NaN,NaN,NaN,NaN,1.4727,0.00000,0.0000,0,0,2023-07-07 05:00:05
15552,6832,ADNI3,ADNI3,052_S_6832,52,m12,2021-03-15,LMCI,NaN,Male,...,NaN,NaN,NaN,NaN,1.4727,1.18001,14.1311,12,12,2023-07-07 05:00:05
15969,6598,ADNI3,ADNI3,053_S_6598,53,m42,2022-06-20,LMCI,NaN,Male,...,NaN,1.38965,NaN,1.4515,NaN,3.66051,43.8361,42,42,2023-07-09 05:25:36

In [23]:
righe_age_mancante = df[df["AGE"].isna()]
print(f"Numero di righe con AGE mancante: {len(righe_age_mancante)}")
righe_age_mancante[["PTID", "VISCODE", "AGE"]]  # sostituisci con le colonne che ti interessano

Numero di righe con AGE mancante: 9

             PTID VISCODE  AGE
13181  053_S_6861      bl  NaN
13290  053_S_6861     m12  NaN
15212  029_S_6505      bl  NaN
15349  053_S_6598      bl  NaN
15350  053_S_6598     m12  NaN
15351  053_S_6598     m30  NaN
15551  052_S_6832      bl  NaN
15552  052_S_6832     m12  NaN
15969  053_S_6598     m42  NaN

Visualizzare righe con età maggiore di 95

In [24]:
righe_over_95 = df[df["AGE"] > 95]
print(f"Numero di righe con età superiore a 95 anni: {len(righe_over_95)}")
righe_over_95

Numero di righe con età superiore a 95 anni: 0

Empty DataFrame
Columns: [RID, COLPROT, ORIGPROT, PTID, SITE, VISCODE, EXAMDATE, DX_bl, AGE, PTGENDER, PTEDUCAT, PTETHCAT, PTRACCAT, PTMARRY, APOE4, FDG, PIB, AV45, FBB, ABETA, TAU, PTAU, CDRSB, ADAS11, ADAS13, ADASQ4, MMSE, RAVLT_immediate, RAVLT_learning, RAVLT_forgetting, RAVLT_perc_forgetting, LDELTOTAL, DIGITSCOR, TRABSCOR, FAQ, MOCA, EcogPtMem, EcogPtLang, EcogPtVisspat, EcogPtPlan, EcogPtOrgan, EcogPtDivatt, EcogPtTotal, EcogSPMem, EcogSPLang, EcogSPVisspat, EcogSPPlan, EcogSPOrgan, EcogSPDivatt, EcogSPTotal, FLDSTRENG, FSVERSION, IMAGEUID, Ventricles, Hippocampus, WholeBrain, Entorhinal, Fusiform, MidTemp, ICV, DX, mPACCdigit, mPACCtrailsB, EXAMDATE_bl, CDRSB_bl, ADAS11_bl, ADAS13_bl, ADASQ4_bl, MMSE_bl, RAVLT_immediate_bl, RAVLT_learning_bl, RAVLT_forgetting_bl, RAVLT_perc_forgetting_bl, LDELTOTAL_BL, DIGITSCOR_bl, TRABSCOR_bl, FAQ_bl, mPACCdigit_bl, mPACCtrailsB_bl, FLDSTRENG_bl, FSVERSION_bl, IMAGEUID_bl, Ventricles_bl, Hippocampus_bl, WholeBrain_bl, Entorhinal_bl, Fusiform_bl, MidTemp_bl, ICV_bl, MOCA_bl, EcogPtMem_bl, EcogPtLang_bl, EcogPtVisspat_bl, EcogPtPlan_bl, EcogPtOrgan_bl, EcogPtDivatt_bl, EcogPtTotal_bl, EcogSPMem_bl, EcogSPLang_bl, EcogSPVisspat_bl, ...]
Index: []

[0 rows x 116 columns]

Età minima,età massima

In [25]:
eta_minima = df["AGE"].min()
eta_massima = df["AGE"].max()

print(f"Età minima: {eta_minima}")
print(f"Età massima: {eta_massima}")

Età minima: 50.4
Età massima: 91.4