In [1]:
import pandas as pd

In [2]:
# --- 1. Caricamento dei dataset puliti ---
adnimerge = pd.read_csv("ADNIMERGE_cleaned_02.csv", parse_dates=["EXAMDATE", "update_stamp"])
ptdemog = pd.read_csv("PTDEMOG_cleaned_02.csv", parse_dates=["EXAMDATE", "update_stamp", "PTDOB"])

In [3]:
adnimerge.dtypes

RID                         int64
COLPROT                       str
VISCODE                       str
EXAMDATE           datetime64[us]
AGE                       float64
EDUCATION                   int64
APOE4                     float64
CDRSB                     float64
ADAS11                    float64
ADAS13                    float64
MMSE                      float64
RAVLT_immediate           float64
FAQ                       float64
FSVERSION                 float64
IMAGEUID                  float64
Ventricles                float64
Hippocampus               float64
Entorhinal                float64
Fusiform                  float64
MidTemp                   float64
ICV                       float64
update_stamp       datetime64[us]
GENDER_0                    int64
GENDER_1                    int64
MARRY_0                     int64
MARRY_1                     int64
MARRY_2                     int64
MARRY_3                     int64
ETHNICITY_0                 int64
ETHNICITY_1                 int64
RACE_0                      int64
RACE_1                      int64
RACE_2                      int64
RACE_3                      int64
RACE_4                      int64
RACE_5                      int64
DX_0                        int64
DX_1                        int64
DX_2                        int64
VISIT_MONTH                 int64
AGE_bl                    float64
dtype: object

In [4]:
ptdemog.dtypes

PTID                       str
RID                      int64
VISCODE                    str
EXAMDATE        datetime64[us]
PTDOB           datetime64[us]
EDUCATION              float64
AGE                    float64
PTADBEG                float64
PTCOGBEG               float64
DX                     float64
HAS_QC_ERROR           float64
update_stamp    datetime64[us]
GENDER_0                 int64
GENDER_1                 int64
MARRY_0                  int64
MARRY_1                  int64
MARRY_2                  int64
MARRY_3                  int64
ETHNICITY_0              int64
ETHNICITY_1              int64
RACE_0                   int64
RACE_1                   int64
RACE_2                   int64
RACE_3                   int64
RACE_4                   int64
RACE_5                   int64
VISIT_MONTH            float64
dtype: object

In [4]:
keys = ["RID", "EXAMDATE"]

# Conto delle combinazioni uniche di chiavi
left_keys = adnimerge[keys].drop_duplicates()
right_keys = ptdemog[keys].drop_duplicates()

key_match = left_keys.merge(
    right_keys,
    on=keys,
    how="outer",
    indicator=True
)

counts = key_match["_merge"].value_counts()
print("Conteggio chiavi uniche per [RID, EXAMDATE]:")
print(counts)

print(f"Match: {counts.get('both', 0)}")
print(f"Solo in adnimerge: {counts.get('left_only', 0)}")
print(f"Solo in ptdemog: {counts.get('right_only', 0)}")

Conteggio chiavi uniche per [RID, EXAMDATE]:
_merge
left_only     8861
right_only    5515
both           445
Name: count, dtype: int64
Match: 445
Solo in adnimerge: 8861
Solo in ptdemog: 5515

In [5]:

# --- 2. Merge su RID + EXAMDATE ---
merged = pd.merge(
    adnimerge,
    ptdemog,
    on=keys,
    how="outer",
    indicator=True
)

In [6]:
# --- 3. Log di controllo post-merge ---
print(merged["_merge"].value_counts())
#merged = merged.drop(columns="_merge") #tenere per le visualizazioni eliminare solo alla fine

_merge
left_only     8861
right_only    5515
both           445
Name: count, dtype: int64

In [38]:
merged = merged[sorted(merged.columns)]
merged[merged["_merge"] == "right_only"]

,ADAS11,ADAS13,AGE,AGE_bl,AGE_x,AGE_y,APOE4,CDRSB,COLPROT,DX,...,VISCODE_x,VISCODE_y,VISIT_MONTH,VISIT_MONTH_x,VISIT_MONTH_y,Ventricles,_merge,update_stamp,update_stamp_x,update_stamp_y
0,NaN,NaN,60.711841,NaN,NaN,60.711841,NaN,NaN,NaN,NaN,...,NaN,f,0.0,NaN,0.0,NaN,right_only,2005-08-18 00:00:00,NaT,2005-08-18 00:00:00
1,NaN,NaN,74.379192,NaN,NaN,74.379192,NaN,NaN,NaN,NaN,...,NaN,sc,0.0,NaN,0.0,NaN,right_only,2005-08-17 00:00:00,NaT,2005-08-17 00:00:00
3,NaN,NaN,79.477070,NaN,NaN,79.477070,NaN,NaN,NaN,NaN,...,NaN,sc,61.0,NaN,61.0,NaN,right_only,2013-03-22 15:23:58,NaT,2013-03-22 15:23:58
4,NaN,NaN,80.468172,NaN,NaN,80.468172,NaN,NaN,NaN,NaN,...,NaN,m72,73.0,NaN,73.0,NaN,right_only,2013-05-30 10:05:05,NaT,2013-05-30 10:05:05
5,NaN,NaN,81.297741,NaN,NaN,81.297741,NaN,NaN,NaN,NaN,...,NaN,sc,0.0,NaN,0.0,NaN,right_only,2005-08-18 00:00:00,NaT,2005-08-18 00:00:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14816,NaN,NaN,74.340862,NaN,NaN,74.340862,NaN,NaN,NaN,NaN,...,NaN,sc,0.0,NaN,0.0,NaN,right_only,2026-02-26 00:04:48,NaT,2026-02-26 00:04:48
14817,NaN,NaN,76.585900,NaN,NaN,76.585900,NaN,NaN,NaN,NaN,...,NaN,sc,0.0,NaN,0.0,NaN,right_only,2026-02-26 00:04:48,NaT,2026-02-26 00:04:48
14818,NaN,NaN,79.600274,NaN,NaN,79.600274,NaN,NaN,NaN,NaN,...,NaN,sc,0.0,NaN,0.0,NaN,right_only,2026-02-26 00:04:48,NaT,2026-02-26 00:04:48
14819,NaN,NaN,67.356605,NaN,NaN,67.356605,NaN,NaN,NaN,NaN,...,NaN,sc,0.0,NaN,0.0,NaN,right_only,2026-02-26 00:04:48,NaT,2026-02-26 00:04:48
14820,NaN,NaN,81.538672,NaN,NaN,81.538672,NaN,NaN,NaN,NaN,...,NaN,sc,0.0,NaN,0.0,NaN,right_only,2026-02-26 00:04:48,NaT,2026-02-26 00:04:48

In [39]:
merged

,ADAS11,ADAS13,AGE,AGE_bl,AGE_x,AGE_y,APOE4,CDRSB,COLPROT,DX,...,VISCODE_x,VISCODE_y,VISIT_MONTH,VISIT_MONTH_x,VISIT_MONTH_y,Ventricles,_merge,update_stamp,update_stamp_x,update_stamp_y
0,NaN,NaN,60.711841,NaN,NaN,60.711841,NaN,NaN,NaN,NaN,...,NaN,f,0.0,NaN,0.0,NaN,right_only,2005-08-18 00:00:00,NaT,2005-08-18 00:00:00
1,NaN,NaN,74.379192,NaN,NaN,74.379192,NaN,NaN,NaN,NaN,...,NaN,sc,0.0,NaN,0.0,NaN,right_only,2005-08-17 00:00:00,NaT,2005-08-17 00:00:00
2,10.67,18.67,74.300000,74.3,74.3,NaN,0.0,0.0,ADNI1,NaN,...,bl,NaN,0.0,0.0,NaN,118233.0,left_only,2023-07-07 04:59:40,2023-07-07 04:59:40,NaT
3,NaN,NaN,79.477070,NaN,NaN,79.477070,NaN,NaN,NaN,NaN,...,NaN,sc,61.0,NaN,61.0,NaN,right_only,2013-03-22 15:23:58,NaT,2013-03-22 15:23:58
4,NaN,NaN,80.468172,NaN,NaN,80.468172,NaN,NaN,NaN,NaN,...,NaN,m72,73.0,NaN,73.0,NaN,right_only,2013-05-30 10:05:05,NaT,2013-05-30 10:05:05
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14816,NaN,NaN,74.340862,NaN,NaN,74.340862,NaN,NaN,NaN,NaN,...,NaN,sc,0.0,NaN,0.0,NaN,right_only,2026-02-26 00:04:48,NaT,2026-02-26 00:04:48
14817,NaN,NaN,76.585900,NaN,NaN,76.585900,NaN,NaN,NaN,NaN,...,NaN,sc,0.0,NaN,0.0,NaN,right_only,2026-02-26 00:04:48,NaT,2026-02-26 00:04:48
14818,NaN,NaN,79.600274,NaN,NaN,79.600274,NaN,NaN,NaN,NaN,...,NaN,sc,0.0,NaN,0.0,NaN,right_only,2026-02-26 00:04:48,NaT,2026-02-26 00:04:48
14819,NaN,NaN,67.356605,NaN,NaN,67.356605,NaN,NaN,NaN,NaN,...,NaN,sc,0.0,NaN,0.0,NaN,right_only,2026-02-26 00:04:48,NaT,2026-02-26 00:04:48
14820,NaN,NaN,81.538672,NaN,NaN,81.538672,NaN,NaN,NaN,NaN,...,NaN,sc,0.0,NaN,0.0,NaN,right_only,2026-02-26 00:04:48,NaT,2026-02-26 00:04:48

Da studiare:
1. per le righe _merge = both --> corrispondono? disugualgianze? origine differenze?
2. capire come unire e togliere _x e _y e avere 1 sola variabile.
3. Che faccio per un soggetto che ha 1 visita in Adnimerge e 3 separate per PTDEMOG? e casi simili? o meglio per una riga solo right o una solo left

### Ragionamento dati non coerenti
I dati anagrafici non coincidono perché sono stati aggiornati in anni/mesi diversi, il giorno dell'esame rimane invariato. Da pensare quale dei dati ci interessa di più, se quella più aggiornata o quella più vicina all'esame eseguito. Valutare anche se potrebbe essere utile utilizzarle entrambe.

In [8]:
both_rows = merged[sorted(merged.columns)]
both_rows[both_rows["_merge"] == "both"]

,ADAS11,ADAS13,AGE_bl,AGE_x,AGE_y,APOE4,CDRSB,COLPROT,DX,DX_0,...,RAVLT_immediate,RID,VISCODE_x,VISCODE_y,VISIT_MONTH_x,VISIT_MONTH_y,Ventricles,_merge,update_stamp_x,update_stamp_y
77,2.0,4.0,72.6,77.552772,77.678303,0.0,0.0,ADNIGO,NaN,1.0,...,58.0,21,m60,sc,59.0,60.0,18783.0,both,2023-07-07 04:59:41,2014-07-10 19:03:08
78,3.0,5.0,72.6,78.560301,78.685832,0.0,0.0,ADNI2,NaN,1.0,...,53.0,21,m72,m72,72.0,72.0,22013.0,both,2023-07-07 04:59:41,2013-05-30 10:05:05
96,5.0,10.0,71.7,76.817043,76.969199,0.0,0.0,ADNIGO,NaN,1.0,...,42.0,23,m60,sc,61.0,62.0,28003.0,both,2023-07-07 04:59:41,2013-03-22 15:23:58
97,6.0,10.0,71.7,77.813621,77.965777,0.0,0.0,ADNI2,NaN,1.0,...,39.0,23,m72,m72,73.0,74.0,29028.0,both,2023-07-07 04:59:41,2013-05-30 10:05:05
124,5.0,10.0,77.7,82.803354,82.915811,0.0,0.0,ADNIGO,NaN,1.0,...,53.0,31,m60,sc,61.0,62.0,31653.0,both,2023-07-07 04:59:41,2014-01-15 19:03:02
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6833,8.0,12.0,70.2,71.182888,71.321013,0.0,1.0,ADNI2,NaN,0.0,...,32.0,2396,m12,m12,12.0,13.0,49461.0,both,2023-07-07 04:59:53,2013-05-30 10:05:05
6842,14.0,26.0,71.5,72.529432,72.646133,2.0,4.0,ADNI2,NaN,0.0,...,28.0,2398,m12,m12,12.0,13.0,59320.0,both,2023-07-07 04:59:53,2013-05-30 10:05:05
6851,14.0,24.0,79.1,80.118480,80.298426,0.0,4.5,ADNI2,NaN,0.0,...,26.0,2403,m12,m12,12.0,14.0,39370.0,both,2023-07-07 04:59:53,2013-05-30 10:05:05
6859,10.0,16.0,71.6,72.596578,72.687201,0.0,0.5,ADNI2,NaN,0.0,...,47.0,2405,m12,m12,12.0,13.0,24946.0,both,2023-07-07 04:59:53,2013-05-30 10:05:05
6866,10.0,15.0,68.0,69.013005,69.108830,0.0,0.5,ADNI2,NaN,0.0,...,23.0,2407,m12,m12,12.0,13.0,18356.0,both,2023-07-07 04:59:53,2013-05-30 10:05:05

In [9]:
cols_x = sorted([c for c in both_rows.columns if c.endswith('_x')])
coppie = []
for c in cols_x:
    base = c[:-2]
    c_y = base + '_y'
    if c_y in both_rows.columns:
        coppie.append(base)

print("Coppie trovate:", coppie)

Coppie trovate: ['AGE', 'EDUCATION', 'ETHNICITY_0', 'ETHNICITY_1', 'GENDER_0', 'GENDER_1', 'MARRY_0', 'MARRY_1', 'MARRY_2', 'MARRY_3', 'RACE_0', 'RACE_1', 'RACE_2', 'RACE_3', 'RACE_4', 'RACE_5', 'VISCODE', 'VISIT_MONTH', 'update_stamp']

In [10]:
# --- 2. Confronta ogni coppia, con tolleranza SOLO per le colonne numeriche ---
for base in coppie:
    col_x, col_y = f"{base}_x", f"{base}_y"

    if pd.api.types.is_numeric_dtype(both_rows[col_x]) and pd.api.types.is_numeric_dtype(both_rows[col_y]):
        diff_mask = (both_rows[col_x] - both_rows[col_y]).abs() > 0.01   # tolleranza per float
    else:
        diff_mask = both_rows[col_x] != both_rows[col_y]                # confronto esatto per stringhe/categorie

    n_diff = diff_mask.sum()
    print(f"{base}: {n_diff} righe diverse su {len(both_rows)}")

    if n_diff > 0:
        print(both_rows.loc[diff_mask, ['RID', col_x, col_y]].head(10))
        print()

AGE: 445 righe diverse su 14821
     RID      AGE_x      AGE_y
77    21  77.552772  77.678303
78    21  78.560301  78.685832
96    23  76.817043  76.969199
97    23  77.813621  77.965777
124   31  82.803354  82.915811
125   31  83.687680  83.800137
173   42  78.220945  78.362765
234   55  81.797057  82.083504
240   56  74.566461  74.776181
241   56  75.582204  75.791923

EDUCATION: 4 righe diverse su 14821
       RID  EDUCATION_x  EDUCATION_y
1631   376         15.0         14.0
2645   625          6.0          8.0
6011  2079         13.0         12.0
6371  2210         12.0         13.0

ETHNICITY_0: 2 righe diverse su 14821
       RID  ETHNICITY_0_x  ETHNICITY_0_y
5856  2022            0.0            1.0
6175  2146            0.0            1.0

ETHNICITY_1: 1 righe diverse su 14821
       RID  ETHNICITY_1_x  ETHNICITY_1_y
6175  2146            1.0            0.0

GENDER_0: 0 righe diverse su 14821
GENDER_1: 0 righe diverse su 14821
MARRY_0: 0 righe diverse su 14821
MARRY_1: 19 righe diverse su 14821
      RID  MARRY_1_x  MARRY_1_y
96     23        0.0        1.0
97     23        0.0        1.0
982   214        1.0        0.0
1359  303        1.0        0.0
1390  311        1.0        0.0
1663  382        1.0        0.0
1796  413        1.0        0.0
2840  673        1.0        0.0
2855  677        1.0        0.0
2884  680        1.0        0.0

MARRY_2: 2 righe diverse su 14821
       RID  MARRY_2_x  MARRY_2_y
4677  1123        1.0        0.0
4678  1123        1.0        0.0

MARRY_3: 17 righe diverse su 14821
      RID  MARRY_3_x  MARRY_3_y
96     23        1.0        0.0
97     23        1.0        0.0
982   214        0.0        1.0
1359  303        0.0        1.0
1390  311        0.0        1.0
1663  382        0.0        1.0
1796  413        0.0        1.0
2855  677        0.0        1.0
2884  680        0.0        1.0
4118  989        0.0        1.0

RACE_0: 1 righe diverse su 14821
       RID  RACE_0_x  RACE_0_y
5856  2022       1.0       0.0

RACE_1: 1 righe diverse su 14821
       RID  RACE_1_x  RACE_1_y
5983  2072       1.0       0.0

RACE_2: 0 righe diverse su 14821
RACE_3: 0 righe diverse su 14821
RACE_4: 0 righe diverse su 14821
RACE_5: 2 righe diverse su 14821
       RID  RACE_5_x  RACE_5_y
5856  2022       0.0       1.0
5983  2072       0.0       1.0

VISCODE: 14523 righe diverse su 14821
   RID VISCODE_x VISCODE_y
0    1       NaN         f
1    2       NaN        sc
2    2        bl       NaN
3    2       NaN        sc
4    2       NaN       m72
5    3       NaN        sc
6    3        bl       NaN
7    3       m06       NaN
8    3       m12       NaN
9    3       m24       NaN

VISIT_MONTH: 429 righe diverse su 14821
     RID  VISIT_MONTH_x  VISIT_MONTH_y
77    21           59.0           60.0
96    23           61.0           62.0
97    23           73.0           74.0
124   31           61.0           62.0
125   31           72.0           73.0
173   42           65.0           66.0
234   55           76.0           78.0
240   56           60.0           61.0
241   56           72.0           74.0
268   59           60.0           61.0

update_stamp: 14821 righe diverse su 14821
   RID      update_stamp_x      update_stamp_y
0    1                 NaT 2005-08-18 00:00:00
1    2                 NaT 2005-08-17 00:00:00
2    2 2023-07-07 04:59:40                 NaT
3    2                 NaT 2013-03-22 15:23:58
4    2                 NaT 2013-05-30 10:05:05
5    3                 NaT 2005-08-18 00:00:00
6    3 2023-07-07 04:59:40                 NaT
7    3 2023-07-07 04:59:40                 NaT
8    3 2023-07-07 04:59:40                 NaT
9    3 2023-07-07 04:59:40                 NaT

In [42]:
# --- Visualizza EXAMDATE, RID, update_stamp per le righe "both" ---
display_cols = ['RID', 'EXAMDATE', 'update_stamp_x', 'update_stamp_y', '_merge']
merged[merged["_merge"] == "both"][display_cols].head(10)

     RID   EXAMDATE      update_stamp_x      update_stamp_y _merge
77    21 2010-10-07 2023-07-07 04:59:41 2014-07-10 19:03:08   both
78    21 2011-10-10 2023-07-07 04:59:41 2013-05-30 10:05:05   both
96    23 2010-12-21 2023-07-07 04:59:41 2013-03-22 15:23:58   both
97    23 2011-12-20 2023-07-07 04:59:41 2013-05-30 10:05:05   both
124   31 2010-12-01 2023-07-07 04:59:41 2014-01-15 19:03:02   both
125   31 2011-10-20 2023-07-07 04:59:41 2014-01-15 19:19:47   both
173   42 2011-04-13 2023-07-07 04:59:41 2013-11-22 19:19:32   both
234   55 2012-05-01 2023-07-07 04:59:41 2013-05-30 10:05:05   both
240   56 2010-12-10 2023-07-07 04:59:41 2013-03-22 15:23:58   both
241   56 2011-12-16 2023-07-07 04:59:41 2013-05-30 10:05:05   both

### Ragionamento: capire come unire e togliere _x e _y e avere 1 sola variabile.
Codice che riempie i buchi vuoti delle colonne x(ADNIMERGE) senza però poi cancellare la colonna y. E' stata creata una colonna apparte dove è stato eseguito questa modifica per non intaccare al momento gli altri dati, non sono state considerate le riche dove nella variabile _merge sono both.

In [12]:
# --- Blocco 1: controllo conflitti, solo sulle righe 'both' ---
both_mask = merged['_merge'] == 'both'

report_conflitti = {}
for base in coppie:
    col_x, col_y = f"{base}_x", f"{base}_y"
    entrambi_presenti = merged[col_x].notna() & merged[col_y].notna() & both_mask

    if pd.api.types.is_numeric_dtype(merged[col_x]) and pd.api.types.is_numeric_dtype(merged[col_y]):
        conflitto = entrambi_presenti & ((merged[col_x] - merged[col_y]).abs() > 0.01)
    else:
        conflitto = entrambi_presenti & (merged[col_x] != merged[col_y])

    report_conflitti[base] = conflitto.sum()
    print(f"{base}: {conflitto.sum()} conflitti su righe 'both'")

AGE: 445 conflitti su righe 'both'
EDUCATION: 4 conflitti su righe 'both'
ETHNICITY_0: 2 conflitti su righe 'both'
ETHNICITY_1: 1 conflitti su righe 'both'
GENDER_0: 0 conflitti su righe 'both'
GENDER_1: 0 conflitti su righe 'both'
MARRY_0: 0 conflitti su righe 'both'
MARRY_1: 19 conflitti su righe 'both'
MARRY_2: 2 conflitti su righe 'both'
MARRY_3: 17 conflitti su righe 'both'
RACE_0: 1 conflitti su righe 'both'
RACE_1: 1 conflitti su righe 'both'
RACE_2: 0 conflitti su righe 'both'
RACE_3: 0 conflitti su righe 'both'
RACE_4: 0 conflitti su righe 'both'
RACE_5: 2 conflitti su righe 'both'
VISCODE: 147 conflitti su righe 'both'
VISIT_MONTH: 429 conflitti su righe 'both'
update_stamp: 445 conflitti su righe 'both'

In [13]:
# --- Blocco 2: coalesce, SENZA ancora eliminare _x/_y ---
for base in coppie:
    col_x, col_y = f"{base}_x", f"{base}_y"
    merged[base] = merged[col_x].combine_first(merged[col_y])

In [14]:
# --- Blocco 3 (per dopo, quando avrai deciso): eliminazione _x/_y ---
# merged = merged.drop(columns=[f"{b}_x" for b in coppie] + [f"{b}_y" for b in coppie])

In [15]:
both_rows = merged[sorted(merged.columns)]
both_rows[both_rows["_merge"] == "both"]

,ADAS11,ADAS13,AGE,AGE_bl,AGE_x,AGE_y,APOE4,CDRSB,COLPROT,DX,...,VISCODE_x,VISCODE_y,VISIT_MONTH,VISIT_MONTH_x,VISIT_MONTH_y,Ventricles,_merge,update_stamp,update_stamp_x,update_stamp_y
77,2.0,4.0,77.552772,72.6,77.552772,77.678303,0.0,0.0,ADNIGO,NaN,...,m60,sc,59.0,59.0,60.0,18783.0,both,2023-07-07 04:59:41,2023-07-07 04:59:41,2014-07-10 19:03:08
78,3.0,5.0,78.560301,72.6,78.560301,78.685832,0.0,0.0,ADNI2,NaN,...,m72,m72,72.0,72.0,72.0,22013.0,both,2023-07-07 04:59:41,2023-07-07 04:59:41,2013-05-30 10:05:05
96,5.0,10.0,76.817043,71.7,76.817043,76.969199,0.0,0.0,ADNIGO,NaN,...,m60,sc,61.0,61.0,62.0,28003.0,both,2023-07-07 04:59:41,2023-07-07 04:59:41,2013-03-22 15:23:58
97,6.0,10.0,77.813621,71.7,77.813621,77.965777,0.0,0.0,ADNI2,NaN,...,m72,m72,73.0,73.0,74.0,29028.0,both,2023-07-07 04:59:41,2023-07-07 04:59:41,2013-05-30 10:05:05
124,5.0,10.0,82.803354,77.7,82.803354,82.915811,0.0,0.0,ADNIGO,NaN,...,m60,sc,61.0,61.0,62.0,31653.0,both,2023-07-07 04:59:41,2023-07-07 04:59:41,2014-01-15 19:03:02
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6833,8.0,12.0,71.182888,70.2,71.182888,71.321013,0.0,1.0,ADNI2,NaN,...,m12,m12,12.0,12.0,13.0,49461.0,both,2023-07-07 04:59:53,2023-07-07 04:59:53,2013-05-30 10:05:05
6842,14.0,26.0,72.529432,71.5,72.529432,72.646133,2.0,4.0,ADNI2,NaN,...,m12,m12,12.0,12.0,13.0,59320.0,both,2023-07-07 04:59:53,2023-07-07 04:59:53,2013-05-30 10:05:05
6851,14.0,24.0,80.118480,79.1,80.118480,80.298426,0.0,4.5,ADNI2,NaN,...,m12,m12,12.0,12.0,14.0,39370.0,both,2023-07-07 04:59:53,2023-07-07 04:59:53,2013-05-30 10:05:05
6859,10.0,16.0,72.596578,71.6,72.596578,72.687201,0.0,0.5,ADNI2,NaN,...,m12,m12,12.0,12.0,13.0,24946.0,both,2023-07-07 04:59:53,2023-07-07 04:59:53,2013-05-30 10:05:05
6866,10.0,15.0,69.013005,68.0,69.013005,69.108830,0.0,0.5,ADNI2,NaN,...,m12,m12,12.0,12.0,13.0,18356.0,both,2023-07-07 04:59:53,2023-07-07 04:59:53,2013-05-30 10:05:05

In [16]:
nan_prima = {}
for base in coppie:
    col_x = f"{base}_x"
    nan_prima[base] = merged[col_x].isna().sum()
    print(f"{col_x}: {nan_prima[base]} NaN")

AGE_x: 5521 NaN
EDUCATION_x: 5515 NaN
ETHNICITY_0_x: 5515 NaN
ETHNICITY_1_x: 5515 NaN
GENDER_0_x: 5515 NaN
GENDER_1_x: 5515 NaN
MARRY_0_x: 5515 NaN
MARRY_1_x: 5515 NaN
MARRY_2_x: 5515 NaN
MARRY_3_x: 5515 NaN
RACE_0_x: 5515 NaN
RACE_1_x: 5515 NaN
RACE_2_x: 5515 NaN
RACE_3_x: 5515 NaN
RACE_4_x: 5515 NaN
RACE_5_x: 5515 NaN
VISCODE_x: 5515 NaN
VISIT_MONTH_x: 5515 NaN
update_stamp_x: 5515 NaN

In [17]:
for base in coppie:
    col_y = f"{base}_y"
    nan_prima[base] = merged[col_y].isna().sum()
    print(f"{col_y}: {nan_prima[base]} NaN")

AGE_y: 8862 NaN
EDUCATION_y: 8882 NaN
ETHNICITY_0_y: 8861 NaN
ETHNICITY_1_y: 8861 NaN
GENDER_0_y: 8861 NaN
GENDER_1_y: 8861 NaN
MARRY_0_y: 8861 NaN
MARRY_1_y: 8861 NaN
MARRY_2_y: 8861 NaN
MARRY_3_y: 8861 NaN
RACE_0_y: 8861 NaN
RACE_1_y: 8861 NaN
RACE_2_y: 8861 NaN
RACE_3_y: 8861 NaN
RACE_4_y: 8861 NaN
RACE_5_y: 8861 NaN
VISCODE_y: 8863 NaN
VISIT_MONTH_y: 8862 NaN
update_stamp_y: 8861 NaN

In [18]:
nan_dopo = {}
for base in coppie:
    col_x = f"{base}"
    nan_dopo[base] = merged[col_x].isna().sum()

for base in coppie:
    diff = nan_prima[base] - nan_dopo[base]
    print(f"{base}: NaN prima={nan_prima[base]}, dopo={nan_dopo[base]}  →  riempiti: {diff}")

AGE: NaN prima=8862, dopo=7  →  riempiti: 8855
EDUCATION: NaN prima=8882, dopo=21  →  riempiti: 8861
ETHNICITY_0: NaN prima=8861, dopo=0  →  riempiti: 8861
ETHNICITY_1: NaN prima=8861, dopo=0  →  riempiti: 8861
GENDER_0: NaN prima=8861, dopo=0  →  riempiti: 8861
GENDER_1: NaN prima=8861, dopo=0  →  riempiti: 8861
MARRY_0: NaN prima=8861, dopo=0  →  riempiti: 8861
MARRY_1: NaN prima=8861, dopo=0  →  riempiti: 8861
MARRY_2: NaN prima=8861, dopo=0  →  riempiti: 8861
MARRY_3: NaN prima=8861, dopo=0  →  riempiti: 8861
RACE_0: NaN prima=8861, dopo=0  →  riempiti: 8861
RACE_1: NaN prima=8861, dopo=0  →  riempiti: 8861
RACE_2: NaN prima=8861, dopo=0  →  riempiti: 8861
RACE_3: NaN prima=8861, dopo=0  →  riempiti: 8861
RACE_4: NaN prima=8861, dopo=0  →  riempiti: 8861
RACE_5: NaN prima=8861, dopo=0  →  riempiti: 8861
VISCODE: NaN prima=8863, dopo=2  →  riempiti: 8861
VISIT_MONTH: NaN prima=8862, dopo=1  →  riempiti: 8861
update_stamp: NaN prima=8861, dopo=0  →  riempiti: 8861

In [19]:
base = "AGE"  # sostituisci con una colonna che ti aspetti abbia vuoti
col_x = f"{base}_y"

print(merged[col_x].value_counts(dropna=False).head(20))

AGE_y
NaN          8862
77.270363       5
82.683094       5
72.413415       5
71.370294       5
79.477070       4
73.248460       4
75.805613       4
71.983573       4
72.484600       4
62.902122       4
76.459959       4
70.902122       4
78.376454       4
77.119781       4
75.069131       4
67.832991       4
76.657084       4
72.273785       4
71.039014       4
Name: count, dtype: int64

### Appunto codice precedente
Codice precedente controlla la colonna sbagliata, è stata creata un'altra variabile dove ci sono le unioni dei dati di entrambe, quindi non va controllata direttamente AGE_x

In [20]:
print("NaN in AGE_x:", merged["AGE_x"].isna().sum())
print("NaN in AGE_y:", merged["AGE_y"].isna().sum())
print("NaN in AGE (nuova, coalescata):", merged["AGE"].isna().sum())

NaN in AGE_x: 5521
NaN in AGE_y: 8862
NaN in AGE (nuova, coalescata): 7

In [21]:
print("Conflitti trovati per AGE:", report_conflitti.get("AGE", "non calcolato"))

Conflitti trovati per AGE: 445

### Conflitti appunti
Riposta il numero indicato perchè lo stesso numero dei both che non volevamo venissero toccati

In [22]:
print("NaN in VISCODE_x:", merged["VISCODE_x"].isna().sum())
print("NaN in VISCODE_y:", merged["VISCODE_y"].isna().sum())
print("NaN in VISCODE (nuova, coalescata):", merged["VISCODE"].isna().sum())

NaN in VISCODE_x: 5515
NaN in VISCODE_y: 8863
NaN in VISCODE (nuova, coalescata): 2

In [23]:
print("Conflitti trovati per VISCODE:", report_conflitti.get("VISCODE", "non calcolato"))

Conflitti trovati per VISCODE: 147

In [24]:
print("NaN in EDUCATION_x:", merged["EDUCATION_x"].isna().sum())
print("NaN in EDUCATION_y:", merged["EDUCATION_y"].isna().sum())
print("NaN in EDUCATION (nuova, coalescata):", merged["EDUCATION"].isna().sum())

NaN in EDUCATION_x: 5515
NaN in EDUCATION_y: 8882
NaN in EDUCATION (nuova, coalescata): 21

In [25]:
print(both_rows[["RID", "EXAMDATE"]].head(20))

    RID   EXAMDATE
0     1 2005-08-18
1     2 2005-08-17
2     2 2005-09-08
3     2 2010-09-22
4     2 2011-09-19
5     3 2005-08-18
6     3 2005-09-12
7     3 2006-03-13
8     3 2006-09-12
9     3 2007-09-12
10    4 2005-08-18
11    4 2005-11-08
12    4 2006-05-02
13    4 2006-11-14
14    4 2007-05-14
15    4 2008-11-18
16    5 2005-08-23
17    5 2005-09-07
18    5 2006-03-09
19    5 2006-09-05

### Controllo colonne AGE, varianza

In [26]:
both_rows = merged[merged["_merge"] == "both"]

diff_age = (both_rows["AGE_x"] - both_rows["AGE_y"]).abs()

print(diff_age.describe())   # statistiche riassuntive: min, max, media, quartili

for soglia in [0.05, 0.1, 0.2, 0.3, 0.5, 1]:
    n = (diff_age > soglia).sum()
    print(f"Differenze > {soglia} anni: {n} ({n/len(diff_age):.1%})")

count    445.000000
mean       0.146609
std        0.063244
min        0.024914
25%        0.103285
50%        0.143121
75%        0.176934
max        0.465229
dtype: float64
Differenze > 0.05 anni: 437 (98.2%)
Differenze > 0.1 anni: 339 (76.2%)
Differenze > 0.2 anni: 71 (16.0%)
Differenze > 0.3 anni: 12 (2.7%)
Differenze > 0.5 anni: 0 (0.0%)
Differenze > 1 anni: 0 (0.0%)

In [27]:
print(both_rows[["RID", "AGE_x", "AGE_y"]].assign(
    diff=(both_rows["AGE_x"] - both_rows["AGE_y"])
).groupby("RID")["diff"].mean())

RID
21     -0.125530
23     -0.152156
31     -0.112457
42     -0.141821
55     -0.286448
          ...
2396   -0.138125
2398   -0.116701
2403   -0.179945
2405   -0.090623
2407   -0.095825
Name: diff, Length: 341, dtype: float64

In [28]:
print("NaN in AGE_bl:", merged["AGE_bl"].isna().sum())
print("Totale righe:", len(merged))

NaN in AGE_bl: 5521
Totale righe: 14821

### Appunti AGE_bl
Trovare come inserire i dati dell'età base di PTDEMOG

In [31]:
# --- 1. Crea una mappa RID -> età alla visita baseline (da PTDEMOG) ---
baseline_age = (
    merged.loc[merged["VISCODE"] == "bl", ["RID", "AGE_y"]]
    .dropna(subset=["AGE_y"])
    .drop_duplicates(subset="RID")
    .set_index("RID")["AGE_y"]
)

Problemo, VISCODE non ha "bl"

In [32]:
print(f"Soggetti con età baseline disponibile da PTDEMOG: {len(baseline_age)}")

Soggetti con età baseline disponibile da PTDEMOG: 0

In [34]:
viscode_con_age_y = merged.loc[merged["AGE_y"].notna(), "VISCODE"].dropna().unique()

print(sorted(viscode_con_age_y))

['f', 'm12', 'm126', 'm132', 'm138', 'm144', 'm150', 'm156', 'm162', 'm168', 'm174', 'm18', 'm186', 'm204', 'm210', 'm216', 'm222', 'm228', 'm234', 'm24', 'm240', 'm30', 'm36', 'm42', 'm48', 'm54', 'm60', 'm66', 'm72', 'm78', 'm84', 'm90', 'm96', 'sc']

In [33]:
n_f = (merged["VISCODE"] == "f").sum()
print(f"Righe con VISCODE = 'f' (screen fail): {n_f}")

Righe con VISCODE = 'f' (screen fail): 564

### Appunti VISCODE
Decidere se mappare i codici del VISCODE di PTDEMOG essendo che ha due dati discordanti, "f" e "sc", che sono rispettivamente f=paziente che è stato scartato dallo studio, failed, e sc=screening iniziale prima della baseline
#
Dopo alcune analisi ritengo non necessaria la mappatura
Visionando VISCODE che unisce VISCODE_x e VISCODE_y mi rendo conto che sulla variabile creata per unire i due campi quei buchi vengono riempiti correttamente senza il bisogno di ulteriori modifiche

In [43]:
print(merged.loc[merged["RID"] == 2, ["RID", "VISCODE_y"]])

   RID VISCODE_y
1    2        sc
2    2       NaN
3    2        sc
4    2       m72

In [52]:
display_cols = ['RID', 'EXAMDATE', 'VISCODE', 'VISCODE_y', 'VISCODE_x', '_merge']
merged[display_cols].head(30)

    RID   EXAMDATE VISCODE VISCODE_y VISCODE_x      _merge
0     1 2005-08-18       f         f       NaN  right_only
1     2 2005-08-17      sc        sc       NaN  right_only
2     2 2005-09-08      bl       NaN        bl   left_only
3     2 2010-09-22      sc        sc       NaN  right_only
4     2 2011-09-19     m72       m72       NaN  right_only
5     3 2005-08-18      sc        sc       NaN  right_only
6     3 2005-09-12      bl       NaN        bl   left_only
7     3 2006-03-13     m06       NaN       m06   left_only
8     3 2006-09-12     m12       NaN       m12   left_only
9     3 2007-09-12     m24       NaN       m24   left_only
10    4 2005-08-18      sc        sc       NaN  right_only
11    4 2005-11-08      bl       NaN        bl   left_only
12    4 2006-05-02     m06       NaN       m06   left_only
13    4 2006-11-14     m12       NaN       m12   left_only
14    4 2007-05-14     m18       NaN       m18   left_only
15    4 2008-11-18     m36       NaN       m36   left_only
16    5 2005-08-23      sc        sc       NaN  right_only
17    5 2005-09-07      bl       NaN        bl   left_only
18    5 2006-03-09     m06       NaN       m06   left_only
19    5 2006-09-05     m12       NaN       m12   left_only
20    5 2007-09-07     m24       NaN       m24   left_only
21    5 2008-09-10     m36       NaN       m36   left_only
22    6 2005-11-07      sc        sc       NaN  right_only
23    6 2005-11-29      bl       NaN        bl   left_only
24    6 2006-06-01     m06       NaN       m06   left_only
25    6 2006-11-20     m12       NaN       m12   left_only
26    6 2007-05-15     m18       NaN       m18   left_only
27    6 2008-12-08     m36       NaN       m36   left_only
28    7 2005-08-25      sc        sc       NaN  right_only
29    7 2005-10-06      bl       NaN        bl   left_only

In [59]:
display_cols = ['RID', 'EXAMDATE', 'VISCODE', 'VISCODE_y', 'VISCODE_x', '_merge']
merged[merged["_merge"] == "both"][display_cols].head(30)

     RID   EXAMDATE VISCODE VISCODE_y VISCODE_x _merge
77    21 2010-10-07     m60        sc       m60   both
78    21 2011-10-10     m72       m72       m72   both
96    23 2010-12-21     m60        sc       m60   both
97    23 2011-12-20     m72       m72       m72   both
124   31 2010-12-01     m60        sc       m60   both
125   31 2011-10-20     m72       m72       m72   both
173   42 2011-04-13     m60       m60       m60   both
234   55 2012-05-01     m72       m72       m72   both
240   56 2010-12-10     m60        sc       m60   both
241   56 2011-12-16     m72       m72       m72   both
268   59 2010-12-10     m60        sc       m60   both
269   59 2011-12-16     m72       m72       m72   both
286   61 2011-02-07     m60        sc       m60   both
287   61 2012-02-07     m72       m72       m72   both
310   68 2011-01-10     m60        sc       m60   both
316   69 2011-01-18     m60        sc       m60   both
317   69 2012-01-09     m72       m72       m72   both
336   72 2012-01-10     m72       m72       m72   both
348   74 2010-12-27     m60        sc       m60   both
413   89 2010-09-28     m48        sc       m48   both
414   89 2011-10-05     m72       m72       m72   both
451   96 2011-01-31     m60        sc       m60   both
452   96 2012-02-03     m72       m72       m72   both
473  101 2012-02-16     m72       m72       m72   both
491  106 2012-01-25     m72       m72       m72   both
502  107 2011-06-08     m60       m60       m60   both
512  108 2011-02-15     m60        sc       m60   both
513  108 2012-02-07     m72       m72       m72   both
534  112 2011-01-21     m60        sc       m60   both
544  113 2012-03-08     m72       m72       m72   both

In [58]:
display_cols = ['RID', 'EXAMDATE', 'VISCODE', 'VISCODE_y', 'VISCODE_x', '_merge']
merged[merged["RID"] == 89][display_cols].head(20)

     RID   EXAMDATE VISCODE VISCODE_y VISCODE_x      _merge
407   89 2006-01-18      sc        sc       NaN  right_only
408   89 2006-01-31      bl       NaN        bl   left_only
409   89 2006-08-24     m06       NaN       m06   left_only
410   89 2007-02-15     m12       NaN       m12   left_only
411   89 2008-02-06     m24       NaN       m24   left_only
412   89 2009-02-05     m36       NaN       m36   left_only
413   89 2010-09-28     m48        sc       m48        both
414   89 2011-10-05     m72       m72       m72        both
415   89 2012-10-09     m84       NaN       m84   left_only
416   89 2013-11-22     m96       NaN       m96   left_only
417   89 2015-02-18    m108       NaN      m108   left_only
418   89 2023-11-29    m216      m216       NaN  right_only

CODICE VECCHIO
----------------------------------------------------------------------------------------------------------

In [ ]:
# --- 4. Individuazione righe duplicate sulla chiave, nel risultato finale ---
dup_mask = merged.duplicated(subset=keys, keep=False)   # keep=False: marca TUTTE le occorrenze coinvolte
dup_rows = merged[dup_mask].sort_values(keys)

In [ ]:
print(f"Righe coinvolte in duplicati su {keys}: {dup_mask.sum()} su {len(merged)}")

In [ ]:
# --- 5. Esportazione in CSV ---
merged.to_csv("ADNIMERGE_PTDEMOG_merged_01.csv", index=False, encoding="utf-8-sig")
dup_rows.to_csv("ADNIMERGE_PTDEMOG_duplicati_01.csv", index=False, encoding="utf-8-sig")

In [ ]:
print(f"\nFile salvato: ADNIMERGE_PTDEMOG_merged.csv — {merged.shape[0]} righe, {merged.shape[1]} colonne")
print(f"File duplicati salvato: ADNIMERGE_PTDEMOG_duplicati.csv — {dup_rows.shape[0]} righe")

Controlla PTDOB

In [ ]:
import pandas as pd

df = pd.read_csv("ADNIMERGE_cleaned_02.csv")  # o il nome/percorso corretto del tuo file PTDEMOG

In [ ]:
# --- Ispezione colonna EXAMDATE prima del parsing ---
print("Dtype pandas:", df["EXAMDATE"].dtype)
print("\nPrimi valori non nulli:")
print(df["EXAMDATE"].dropna().unique()[:10])

print("\nType dell'oggetto Python contenuto (primo valore valido):")
primo_valido = df["EXAMDATE"].dropna().iloc[0]
print(type(primo_valido), "->", primo_valido)

print("\nConteggio valori nulli:", df["EXAMDATE"].isna().sum())

In [ ]:
print(df["EXAMDATE"].dropna().unique()[:10])
print(df["update_stamp"].dropna().unique()[:10])